/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

void *sub_140001000();
void *sub_140001010();
int sub_140001020(char *Format, ...);
int scanf(const char *const Format, ...);
__int64 __fastcall sub_1400010E0(__int64 a1, __int64 a2);
const char *__fastcall sub_140001120(__int64 a1);
char *__fastcall sub_140001140(char *Block, char a2);
__int64 __fastcall sub_140001190(_QWORD *a1);
_QWORD *__fastcall sub_1400011B0(_QWORD *a1);
void __noreturn sub_1400011E0(); // weak
__int64 __fastcall sub_140001200(__int64 a1, __int64 a2);
__int64 __fastcall sub_140001240(__int64 a1, __int64 a2);
// __int64 __fastcall XMMI2_FP_Emulation(_QWORD); weak
__int64 __fastcall sub_1400015B0(__int64 a1);
// __int64 __fastcall sub_1400015C0(unsigned __int8 *a1);
int __fastcall main(int argc, const char **argv, const char **envp);
// void __fastcall sub_1400017D0(__int64 a1);
// __int64 __fastcall sub_1400018A0(_QWORD); weak
// __int64 __fastcall sub_140001A60(); weak
// __int64 __fastcall sub_140001AA0(_QWORD); weak
// __int64 __fastcall sub_140001CC0(_QWORD); weak
// void __cdecl j_j_free(void *Block);
// void __stdcall __noreturn CxxThrowException(void *pExceptionObject, _ThrowInfo *pThrowInfo);
__int64 __fastcall sub_140002B80(__int64 a1, __int64 a2);
__int64 __fastcall sub_140002B90(__int64 a1, __int64 a2);
__int64 __fastcall sub_140002B9C(__int64 a1, __int64 a2);
// __int64 __fastcall std::ostream::operator<<(_QWORD, _QWORD); weak
// __int64 __fastcall _std_exception_copy(_QWORD); weak
// __int64 __fastcall _std_exception_destroy(_QWORD); weak

//-------------------------------------------------------------------------
// Data declarations

// extern FILE *(__cdecl *_acrt_iob_func)(unsigned int Ix);
// extern int (__cdecl *_stdio_common_vfprintf)(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list ArgList);
// extern int (__cdecl *_stdio_common_vfscanf)(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list Arglist);
void *std::exception::`vftable' = &sub_140001140; // weak
void *std::bad_alloc::`vftable' = &sub_140001140; // weak
void *std::bad_array_new_length::`vftable' = &sub_140001140; // weak
const _ThrowInfo _TI3_AVbad_array_new_length_std__ = { 0u, 4496, 0, 15888 }; // idb
_UNKNOWN unk_1400057E8; // weak
_UNKNOWN unk_1400057F0; // weak

int __fastcall main(int argc, const char **argv, const char **envp)
{
  __int64 v3; // rax
  __int64 v4; // rax
  const CHAR *v5; // r11
  __int64 v6; // r10
  int v7; // r9d
  const CHAR *v8; // r10
  __int64 v9; // rcx
  __int64 v10; // rax
  unsigned int v12; // ecx
  __int64 v13; // r9
  __int64 v14; // r8
  __int64 v15; // rdx
  __int128 v16[2]; // [rsp+20h] [rbp-38h] BYREF

  memset(v16, 0, sizeof(v16));
  scanf("%s", v16);
  v3 = -1i64;
  do
    ++v3;
  while ( *((_BYTE *)v16 + v3) );
  if ( v3 != 31 )
  {
    while ( 1 )
      Sleep(0x3E8u);
  }
  v4 = XMMI2_FP_Emulation(v16);
  v5 = name;
  if ( v4 )
  {
    sub_1400015C0(*(unsigned __int8 **)(v4 + 8));
    sub_1400015C0(*(unsigned __int8 **)(v6 + 16));
    v7 = dword_1400057E0;
    v5[dword_1400057E0] = *v8;
    dword_1400057E0 = v7 + 1;
  }
  UnDecorateSymbolName(v5, outputString, 0x100u, 0);
  v9 = -1i64;
  do
    ++v9;
  while ( outputString[v9] );
  if ( v9 == 62 )
  {
    v12 = 0;
    v13 = 0i64;
    do
    {
      v14 = outputString[v13] % 23;
      if ( a1234567890Qwer[v14] != a46200860044218[v13] )
        _exit(v12);
      v15 = outputString[v13] / 23;
      if ( a1234567890Qwer[v15] != a55565653255552[v13] )
        _exit(v12 * v12);
      ++v12;
      ++v13;
    }
    while ( v12 < 0x3E );
    sub_140001020("flag{MD5(your input)}\n", v15, v14, v13);
    return 0;
  }
  else
  {
    v10 = sub_1400018A0(std::cout);
    std::ostream::operator<<(v10, sub_140001A60);
    return -1;
  }
}

//----- (0000000140001000) ----------------------------------------------------
void *sub_140001000()
{
  return &unk_1400057F0;
}

//----- (0000000140001010) ----------------------------------------------------
void *sub_140001010()
{
  return &unk_1400057E8;
}

//----- (0000000140001020) ----------------------------------------------------
int sub_140001020(char *Format, ...)
{
  FILE *v2; // rbx
  unsigned __int64 *v3; // rax
  va_list va; // [rsp+58h] [rbp+10h] BYREF

  va_start(va, Format);
  v2 = _acrt_iob_func(1u);
  v3 = (unsigned __int64 *)sub_140001000();
  return _stdio_common_vfprintf(*v3, v2, Format, 0i64, va);
}

//----- (0000000140001080) ----------------------------------------------------
int scanf(const char *const Format, ...)
{
  FILE *v2; // rbx
  unsigned __int64 *v3; // rax
  va_list va; // [rsp+58h] [rbp+10h] BYREF

  va_start(va, Format);
  v2 = _acrt_iob_func(0);
  v3 = (unsigned __int64 *)sub_140001010();
  return _stdio_common_vfscanf(*v3, v2, Format, 0i64, va);
}

//----- (00000001400010E0) ----------------------------------------------------
__int64 __fastcall sub_1400010E0(__int64 a1, __int64 a2)
{
  *(_QWORD *)a1 = &std::exception::`vftable';
  *(_OWORD *)(a1 + 8) = 0i64;
  _std_exception_copy(a2 + 8);
  return a1;
}
// 140003108: using guessed type __int64 __fastcall _std_exception_copy(_QWORD);
// 140003308: using guessed type void *std::exception::`vftable';

//----- (0000000140001120) ----------------------------------------------------
const char *__fastcall sub_140001120(__int64 a1)
{
  const char *result; // rax

  result = "Unknown exception";
  if ( *(_QWORD *)(a1 + 8) )
    return *(const char **)(a1 + 8);
  return result;
}

//----- (0000000140001140) ----------------------------------------------------
char *__fastcall sub_140001140(char *Block, char a2)
{
  *(_QWORD *)Block = &std::exception::`vftable';
  _std_exception_destroy(Block + 8);
  if ( (a2 & 1) != 0 )
    j_j_free(Block);
  return Block;
}
// 140003110: using guessed type __int64 __fastcall _std_exception_destroy(_QWORD);
// 140003308: using guessed type void *std::exception::`vftable';

//----- (0000000140001190) ----------------------------------------------------
__int64 __fastcall sub_140001190(_QWORD *a1)
{
  *a1 = &std::exception::`vftable';
  return _std_exception_destroy(a1 + 1);
}
// 140003110: using guessed type __int64 __fastcall _std_exception_destroy(_QWORD);
// 140003308: using guessed type void *std::exception::`vftable';

//----- (00000001400011B0) ----------------------------------------------------
_QWORD *__fastcall sub_1400011B0(_QWORD *a1)
{
  a1[2] = 0i64;
  a1[1] = "bad array new length";
  *a1 = &std::bad_array_new_length::`vftable';
  return a1;
}
// 140003348: using guessed type void *std::bad_array_new_length::`vftable';

//----- (00000001400011E0) ----------------------------------------------------
void __noreturn sub_1400011E0()
{
  __int64 pExceptionObject[5]; // [rsp+20h] [rbp-28h] BYREF

  sub_1400011B0(pExceptionObject);
  CxxThrowException(pExceptionObject, (_ThrowInfo *)&_TI3_AVbad_array_new_length_std__);
}
// 1400011E0: using guessed type void __noreturn sub_1400011E0();
// 1400011E0: using guessed type _QWORD pExceptionObject[5];

//----- (0000000140001200) ----------------------------------------------------
__int64 __fastcall sub_140001200(__int64 a1, __int64 a2)
{
  *(_QWORD *)a1 = &std::exception::`vftable';
  *(_OWORD *)(a1 + 8) = 0i64;
  _std_exception_copy(a2 + 8);
  *(_QWORD *)a1 = &std::bad_array_new_length::`vftable';
  return a1;
}
// 140003108: using guessed type __int64 __fastcall _std_exception_copy(_QWORD);
// 140003308: using guessed type void *std::exception::`vftable';
// 140003348: using guessed type void *std::bad_array_new_length::`vftable';

//----- (0000000140001240) ----------------------------------------------------
__int64 __fastcall sub_140001240(__int64 a1, __int64 a2)
{
  *(_QWORD *)a1 = &std::exception::`vftable';
  *(_OWORD *)(a1 + 8) = 0i64;
  _std_exception_copy(a2 + 8);
  *(_QWORD *)a1 = &std::bad_alloc::`vftable';
  return a1;
}
// 140003108: using guessed type __int64 __fastcall _std_exception_copy(_QWORD);
// 140003308: using guessed type void *std::exception::`vftable';
// 140003320: using guessed type void *std::bad_alloc::`vftable';

//----- (0000000140002B80) ----------------------------------------------------
__int64 __fastcall sub_140002B80(__int64 a1, __int64 a2)
{
  return sub_1400015B0(a2 + 40);
}
// 1400015B0: using guessed type __int64 __fastcall sub_1400015B0(_QWORD);

//----- (0000000140002B90) ----------------------------------------------------
__int64 __fastcall sub_140002B90(__int64 a1, __int64 a2)
{
  return sub_140001CC0(a2 + 32);
}
// 140001CC0: using guessed type __int64 __fastcall sub_140001CC0(_QWORD);

//----- (0000000140002B9C) ----------------------------------------------------
__int64 __fastcall sub_140002B9C(__int64 a1, __int64 a2)
{
  return sub_140001AA0(a2 + 32);
}
// 140001AA0: using guessed type __int64 __fastcall sub_140001AA0(_QWORD);

// nfuncs=108 queued=15 decompiled=15 lumina nreq=0 worse=0 better=0
// ALL OK, 15 function(s) have been successfully decompiled
