/* This file was generated by the Hex-Rays decompiler version 8.3.0.230608.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>

#include <stdarg.h>


//-------------------------------------------------------------------------
// Function declarations

#define __thiscall __cdecl // Test compile in C mode

void *sub_A61000();
void *sub_A61010();
int printf(char *Format, ...);
int scanf(char *Format, ...);
int __cdecl main(int argc, const char **argv, const char **envp);
// int __report_rangecheckfailure(void); weak
int sub_A615CD();
int sub_A615D5();
int __cdecl UserMathErrorFunction();
int sub_A61A5F();
void sub_A61A69();
char sub_A61A75();
// int __scrt_initialize_default_local_stdio_options(void); weak
BOOL sub_A61AB7();
void *sub_A61AC3();
void *sub_A61AC9();
LPTOP_LEVEL_EXCEPTION_FILTER sub_A61C31();
// LONG __stdcall __scrt_unhandled_exception_filter(struct _EXCEPTION_POINTERS *ExceptionInfo); idb
void sub_A61C93();
void sub_A61C9B();
void __cdecl sub_A61CC7(); // idb
// int __cdecl set_new_mode(int NewMode);
// void __userpurge sub_A651D8(int a1, int a2, int a3, int a4, int a5, int a6, int a7, int a8, int a9, int a10, int a11, int a12, int a13, int a14, int a15, int a16, int a17, int a18, int a19, int a20, int a21, int a22, int a23, int a24, int a25, int a26, int a27, int a28, int a29, int a30, int a31, int a32, int a33, int a34, int a35, int a36, int a37, int a38, int a39, int a40, int a41, int a42, int a43, int a44, int a45, int a46, int a47, int a48, int a49, int a50, int a51, int a52, int a53, int a54, int a55, int a56, int a57, int a58, int a59, int a60, int a61, int a62, int a63);
// void __usercall sub_A651FC(char a1@<ah>);

//-------------------------------------------------------------------------
// Data declarations

union _SLIST_HEADER ListHead; // idb
int dword_A63348; // weak
_UNKNOWN unk_A63358; // weak
_UNKNOWN unk_A63360; // weak
_UNKNOWN unk_A63368; // weak
_UNKNOWN unk_A6336C; // weak
// extern LPTOP_LEVEL_EXCEPTION_FILTER (__stdcall *SetUnhandledExceptionFilter)(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
// extern void (__stdcall *InitializeSListHead)(PSLIST_HEADER ListHead);
// extern int (__cdecl *_stdio_common_vfscanf)(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list Arglist);
// extern FILE *(__cdecl *_acrt_iob_func)(unsigned int Ix);
// extern int (__cdecl *_stdio_common_vfprintf)(unsigned __int64 Options, FILE *Stream, const char *Format, _locale_t Locale, va_list ArgList);
int dword_A6500C = 1; // weak


//----- (00A61000) --------------------------------------------------------
void *sub_A61000()
{
  return &unk_A63360;
}

//----- (00A61010) --------------------------------------------------------
void *sub_A61010()
{
  return &unk_A63358;
}

//----- (00A61020) --------------------------------------------------------
int printf(char *Format, ...)
{
  unsigned __int64 *v1; // eax
  FILE *v3; // [esp-10h] [ebp-14h]
  va_list va; // [esp+10h] [ebp+Ch] BYREF

  va_start(va, Format);
  v3 = _acrt_iob_func(1u);
  v1 = sub_A61000();
  return _stdio_common_vfprintf(*v1, v3, Format, 0, va);
}

//----- (00A61050) --------------------------------------------------------
int scanf(char *Format, ...)
{
  unsigned __int64 *v1; // eax
  FILE *v3; // [esp-10h] [ebp-14h]
  va_list va; // [esp+10h] [ebp+Ch] BYREF

  va_start(va, Format);
  v3 = _acrt_iob_func(0);
  v1 = sub_A61010();
  return _stdio_common_vfscanf(*v1, v3, Format, 0, va);
}

//----- (00A61080) --------------------------------------------------------
#error "A611E8: call analysis failed (funcsize=166)"

//----- (00A615CD) --------------------------------------------------------
int sub_A615CD()
{
  __scrt_initialize_default_local_stdio_options();
  return 0;
}
// A61A9A: using guessed type int __scrt_initialize_default_local_stdio_options(void);

//----- (00A615D5) --------------------------------------------------------
int sub_A615D5()
{
  int v0; // eax

  sub_A61C31();
  v0 = UserMathErrorFunction();
  return set_new_mode(v0);
}

//----- (00A61A5C) --------------------------------------------------------
int __cdecl UserMathErrorFunction()
{
  return 0;
}

//----- (00A61A5F) --------------------------------------------------------
int sub_A61A5F()
{
  return 1;
}

//----- (00A61A69) --------------------------------------------------------
void sub_A61A69()
{
  InitializeSListHead(&ListHead);
}

//----- (00A61A75) --------------------------------------------------------
char sub_A61A75()
{
  return 1;
}

//----- (00A61AB7) --------------------------------------------------------
BOOL sub_A61AB7()
{
  return dword_A6500C == 0;
}
// A6500C: using guessed type int dword_A6500C;

//----- (00A61AC3) --------------------------------------------------------
void *sub_A61AC3()
{
  return &unk_A6336C;
}

//----- (00A61AC9) --------------------------------------------------------
void *sub_A61AC9()
{
  return &unk_A63368;
}

//----- (00A61C31) --------------------------------------------------------
LPTOP_LEVEL_EXCEPTION_FILTER sub_A61C31()
{
  return SetUnhandledExceptionFilter(__scrt_unhandled_exception_filter);
}

//----- (00A61C93) --------------------------------------------------------
void sub_A61C93()
{
  dword_A63348 = 0;
}
// A63348: using guessed type int dword_A63348;

//----- (00A61C9B) --------------------------------------------------------
void sub_A61C9B()
{
  ;
}
// A61C9B: could not find valid save-restore pair for edi
// 65FFFE: using guessed type int (__thiscall *)(_DWORD);

//----- (00A61CC7) --------------------------------------------------------
void __cdecl sub_A61CC7()
{
  ;
}
// A61CC7: could not find valid save-restore pair for edi
// 65FFFE: using guessed type int (__thiscall *)(_DWORD);

//----- (00A651D8) --------------------------------------------------------
void __userpurge sub_A651D8(
        int a1,
        int a2,
        int a3,
        int a4,
        int a5,
        int a6,
        int a7,
        int a8,
        int a9,
        int a10,
        int a11,
        int a12,
        int a13,
        int a14,
        int a15,
        int a16,
        int a17,
        int a18,
        int a19,
        int a20,
        int a21,
        int a22,
        int a23,
        int a24,
        int a25,
        int a26,
        int a27,
        int a28,
        int a29,
        int a30,
        int a31,
        int a32,
        int a33,
        int a34,
        int a35,
        int a36,
        int a37,
        int a38,
        int a39,
        int a40,
        int a41,
        int a42,
        int a43,
        int a44,
        int a45,
        int a46,
        int a47,
        int a48,
        int a49,
        int a50,
        int a51,
        int a52,
        int a53,
        int a54,
        int a55,
        int a56,
        int a57,
        int a58,
        int a59,
        int a60,
        int a61,
        int a62,
        int a63)
{
  int i; // edi

  for ( i = 0; i <= 337; ++i )
    *(i + 10899964) ^= 0x72u;
  sub_A651FC(a1);
}
// A651D8: could not find valid save-restore pair for esi

//----- (00A651FC) --------------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __usercall sub_A651FC(char a1@<ah>)
{
  if ( (a1 & 1) == 0 )
    __asm { retf    7273h }
  JUMPOUT(0xA6527B);
}
// A6534D: positive sp value 2C has been found
// A65207: control flows out of bounds to A6527B
// A651FC: using guessed type char var_18[8];

// nfuncs=81 queued=20 decompiled=20 lumina nreq=0 worse=0 better=0
#error "There were 1 decompilation failure(s) on 20 function(s)"
